create table cliente (idcliente int4 generated by default as identity, cpf varchar(15) not null, email varchar(100) not null, nome varchar(150) not null, primary key (idcliente));
create table usuario (idusuario int4 generated by default as identity, email varchar(100) not null, nome varchar(150) not null, senha varchar(50) not null, primary key (idusuario));
alter table if exists cliente add constraint UK_r1u8010d60num5vc8fp0q1j2a unique (cpf);
alter table if exists usuario add constraint UK_5171l57faosmj8myawaucatdw unique (email);
